In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data.csv")
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df[['Actor']]

                 Actor
0       Shah Rukh Khan
1          Salman Khan
2           Aamir Khan
3        Ranbir Kapoor
4        Ranveer Singh
5   Ayushmann Khurrana
6        Rajkummar Rao
7       Hrithik Roshan
8         Akshay Kumar
9        Kartik Aaryan
10        Varun Dhawan
11       Vicky Kaushal

In [4]:
df[['Actor', 'IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [12]:
print(df['Actor'][4])

Ranveer Singh

In [21]:
print(df.loc[0]) # First row (by label)
print('\n\n')
print(df.iloc[0]) # First row (by position)

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object



Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [32]:
df.loc[8, 'Genre']

Genre    Comedy
IMDb        7.0
Name: 8, dtype: object

In [28]:
df.iloc[8, 3]

'Comedy'

In [34]:
df.loc[8, ['Genre', 'IMDb']]

Genre    Comedy
IMDb        7.0
Name: 8, dtype: object

In [35]:
df.loc[3:8, ['Actor', 'Film', 'IMDb']]

                Actor        Film  IMDb
3       Ranbir Kapoor  Brahmastra   5.6
4       Ranveer Singh   Padmaavat   7.0
5  Ayushmann Khurrana   Andhadhun   8.3
6       Rajkummar Rao       Stree   7.5
7      Hrithik Roshan         War   6.5
8        Akshay Kumar  Good Newwz   7.0

In [42]:
df.iloc[3:8, 0:5 ]

                Actor        Film  Year          Genre  BoxOffice(INR Crore)
3       Ranbir Kapoor  Brahmastra  2022        Fantasy                   431
4       Ranveer Singh   Padmaavat  2018     Historical                   585
5  Ayushmann Khurrana   Andhadhun  2018       Thriller                   111
6       Rajkummar Rao       Stree  2018  Horror Comedy                   180
7      Hrithik Roshan         War  2019         Action                   475

In [43]:
df.iloc[3:8,[ 0, 1, 5] ]

                Actor        Film  IMDb
3       Ranbir Kapoor  Brahmastra   5.6
4       Ranveer Singh   Padmaavat   7.0
5  Ayushmann Khurrana   Andhadhun   8.3
6       Rajkummar Rao       Stree   7.5
7      Hrithik Roshan         War   6.5

In [47]:
df.at[0, 'Actor'] #alternative of-> df.loc[0, "Actor"]

'Shah Rukh Khan'

In [48]:
df.iat[0, 0] #alternative of-> df.iloc[0, 0]

'Shah Rukh Khan'

In [50]:
df[df['IMDb']>7]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [54]:
df[df['Genre']=='Comedy']

          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0

In [57]:
df[df['IMDb']>7]['Film']

0                      Pathaan
2                       Dangal
5                    Andhadhun
6                        Stree
11    Uri: The Surgical Strike
Name: Film, dtype: object

In [60]:
df[(df['IMDb']>6) & (df['Year']>=2020)] # AND (&)

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [61]:
df[(df['IMDb']>6) | (df['Year']>=2020)] #OR (|)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [86]:
'''Querying with .query()'''
print("Output 1")
print(df.query("IMDb > 8"))

print("\n\nOutput 2")
print( df.query('IMDb > 7 and Year > 2020'))#and

print("\n\nOutput 3")
print( df.query('IMDb > 8 or Year > 2020'))#or

'''String values must be in quotes'''
print("\n\nOutput 4")
print( df.query('9 > IMDb > 6 and Genre == "Comedy" '))

'''Use backticks for column names with spaces or special characters
If a column name has spaces, use backticks (`):'''
#Ex - df.query("`first name` == 'Alice'")

''' You can use @ to reference Python variables'''
print("\n\nOutput 5")
year = 2018
print(df.query("Year > @year"))

Output 1
                 Actor                      Film  Year      Genre  \
2           Aamir Khan                    Dangal  2016  Biography
5   Ayushmann Khurrana                 Andhadhun  2018   Thriller
11       Vicky Kaushal  Uri: The Surgical Strike  2019     Action

    BoxOffice(INR Crore)  IMDb
2                   2024   8.4
5                    111   8.3
11                   342   8.2


Output 2
            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2


Output 3
                 Actor                      Film  Year          Genre  \
0       Shah Rukh Khan                   Pathaan  2023         Action
2           Aamir Khan                    Dangal  2016      Biography
3        Ranbir Kapoor                Brahmastra  2022        Fantasy
5   Ayushmann Khurrana                 Andhadhun  2018       Thriller
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022  Horror Comedy
11       Vicky Kaushal  Uri: The Surgical Strike  2019         Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
2                   2024   8.4
3                    431   5.6
5                    111   8.3
9                    266   5.9
11                   342   8.2


Output 4
          Actor        Film  Year   Genre  BoxOffice(INR Crore)  IMDb
8  Akshay Kumar  Good Newwz  2019  Comedy                   318   7.0


Output 5
             Actor                      Film  Year          Genre  \
0   Shah Rukh Khan                   Pathaan  2023         Action
3    Ranbir Kapoor                Brahmastra  2022        Fantasy
7   Hrithik Roshan                       War  2019         Action
8     Akshay Kumar                Good Newwz  2019         Comedy
9    Kartik Aaryan         Bhool Bhulaiyaa 2  2022  Horror Comedy
11   Vicky Kaushal  Uri: The Surgical Strike  2019         Action

    BoxOffice(INR Crore)  IMDb
0                   1050   7.2
3                    431   5.6
7                    475   6.5
8                    318   7.0
9                    266   5.9
11                   342   8.2