In [1]:
"""Sorting & Ranking"""
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df.sort_values("Year")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [20]:
df.sort_values('Year', ascending = False) #for decending sort

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [21]:
df.sort_values(["Year", "IMDb"], ascending = False )

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [22]:
df2 = df.sort_values(["Year", "IMDb"], ascending = [True, False] )
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [23]:
df2.reset_index() # to sort the index and also return old index in new column named index

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
7,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,7,Hrithik Roshan,War,2019,Action,475,6.5
9,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [27]:
df2.reset_index(drop = True) # Using drop will not add new column of old index

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [25]:
df2.reset_index(drop = True, inplace = True) # By using 'inplace' we can update the object

In [26]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
3,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
4,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
7,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
8,Hrithik Roshan,War,2019,Action,475,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [32]:
df3 = df.sort_values("BoxOffice(INR Crore)", ascending = False).copy()
df3

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
7,Hrithik Roshan,War,2019,Action,475,6.5
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3

In [33]:
df3.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [35]:
df["Rank"] = df["IMDb"].rank() # Creates a new column with ranking of data based on IMDb in ascending order.
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0

In [38]:
df["Rank"] = df["IMDb"].rank(ascending = False, method = "dense") # method = 'dense' will hwlp to return ranking in int or whole no.
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0

In [40]:
df.rename(columns={"Film":"Movie Name"}, inplace = True) # if we not use inplace = True then we will receive a view 
df

,Actor,Movie Name,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0

In [42]:
df.columns = ["Actor", "Film", "Year", "Type", "BOxOffice(INR Crore)", "IMDb", "Rank"] # Used to change the name of all columns
df

,Actor,Film,Year,Type,BOxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0

In [47]:
df = df[["Film", "Year", "IMDb", "Actor","BOxOffice(INR Crore)", "Type" ]]#reorder columns
df

,Film,Year,IMDb,Actor,BOxOffice(INR Crore),Type
0,Pathaan,2023,7.2,Shah Rukh Khan,1050,Action
1,Tiger Zinda Hai,2017,6.0,Salman Khan,565,Action
2,Dangal,2016,8.4,Aamir Khan,2024,Biography
3,Brahmastra,2022,5.6,Ranbir Kapoor,431,Fantasy
4,Padmaavat,2018,7.0,Ranveer Singh,585,Historical
5,Andhadhun,2018,8.3,Ayushmann Khurrana,111,Thriller
6,Stree,2018,7.5,Rajkummar Rao,180,Horror Comedy
7,War,2019,6.5,Hrithik Roshan,475,Action
8,Good Newwz,2019,7.0,Akshay Kumar,318,Comedy
9,Bhool Bhulaiyaa 2,2022,5.9,Kartik Aaryan,266,Horror Comedy
10,Badrinath Ki Dulhania,2017,6.1,Varun Dhawan,201,Romantic Comedy
11,Uri: The Surgical Strike,2019,8.2,Vicky Kaushal,342,Action