In [2]:
import pandas as pd

In [14]:
"""Mergeing"""
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [6]:
pd.merge(employees, departments, on= "DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [11]:
pd.merge(employees, departments, on= "DeptID", how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [12]:
pd.merge(employees, departments, on = "DeptID", how = "right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [13]:
pd.merge(employees, departments, on = "DeptID", how = "outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [15]:
'''Concatenating DataFrames - Joining'''

df1 = pd.DataFrame({"Name": ["Alice", "Bob"]})
df1

    Name
0  Alice
1    Bob

In [16]:
df2 = pd.DataFrame({"Name": ["Charlie", "David"]})
df2

      Name
0  Charlie
1    David

In [17]:
pd.concat([df1, df2])

      Name
0    Alice
1      Bob
0  Charlie
1    David

In [18]:
pd.concat([df1, df2], axis = 1)

    Name     Name
0  Alice  Charlie
1    Bob    David

In [19]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], "Score" : [556, 784]})
df1

    Name  Score
0  Alice    556
1    Bob    784

In [20]:
df2 = pd.DataFrame({"Name": ["Charlie", "David"], "Age" : [45, 78]})
df2

      Name  Age
0  Charlie   45
1    David   78

In [21]:
pd.concat([df1, df2])

      Name  Score   Age
0    Alice  556.0   NaN
1      Bob  784.0   NaN
0  Charlie    NaN  45.0
1    David    NaN  78.0

In [22]:
pd.concat([df1, df2], axis = 1)

    Name  Score     Name  Age
0  Alice    556  Charlie   45
1    Bob    784    David   78